---
- name: Dev Setup
  host: localhost
  connection: local
  tasks:

#=====================================
# INSTALL PACKAGES
#=====================================
  
    - name: Install standard software
      pacman:
        name:
          - curl
          - wget
          - git

    - name: Install development software
      pacman:
        name:
          # TOOLS
          - neovim
          - zsh
          - dbeaver
          - tmux
          - alacritty
          - github-cli
          # LANGUAGES
          - dotnet-sdk
          - python
          - rust
          - jdk-openjdk
          - nodejs

    - name: Install customization software
      pacman:
        name:
          - polybar
          - mate-panel
          - rofi
          - feh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Install additional software
      pacman:
        name:
          # DAILY TASKS
          - firefox
          - chromium
          - libreoffice-still
          - okular
          - thunar
          - gimp
          - keepasscx
          # BACKGROUND
          - spotify
          - discord

    - name: Install virtualization software
      pacman:
        name:
          - virt-manager

#=====================================
# TIDY SETUP
#=====================================

    - name: Create Coding directory
      file:
        path: ~/Coding
        state: directory

    - name: Create .config directory
      file:
        path: ~/.config
        state: directory

    - name: Create fonts directory
      file:
        path: ~/.local/share/fonts
        state: directory
        recurse: true
    - name: Create Downloads directory
      file:
        path: ~/Downloads
        state: directory

#=====================================
# GET CUSTOMIZATIONS
#=====================================

    #==== INSTALL FONTS ====


    - name: Download Meslo Nerd Font
      git:
        repo: https://github.com/ryanoasis/nerd-fonts.git
        dest: ~/Downloads

    - name: Install Meslo Nerd Font
      shell: cd ~/Downloads && ./install.sh Meslo 

    - name: Install Font Awesome
      pacman:
        name:
          - ttf-font-awesome

    #==== ZSH-PLUGINS ====

    - name: Install powerlevel10k
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

    - name: Install zsh-autosuggestions                                                                                                                                 
      git:                                                                                                                                                              
        repo: https://github.com/zsh-users/zsh-autosuggestions.git                                                                                                      
        dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions                                                                                            
                                                                                                                                                                        
    - name: Install zsh-syntax-highlighting                                                                                                                             
      git:                                                                                                                                                              
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git                                                                                                  
        dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting                                                                                        
                                                                                                                                                                        
    - name: Install zsh-completions                                                                                                                                     
      git:                                                                                                                                                              
        repo: https://github.com/zsh-users/zsh-completions.git                                                                                                          
        dest: ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions

    - name: Install zsh-history-substring-search
      git:
        repo: https://github.com/zsh-users/zsh-history-substring-search.git
        dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search

    #==== SPICETIFY ====

    - name: Download Spicetify
      shell: curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh

    - name: Download Spicetify themes
      git:
        repo: https://github.com/spicetify/spicetify-themes.git
        dest: ~/Downloads

    - name: Create Spicetify directory
      file:
        path: ~/.config/spicetify/Themes
        state: directory
        recurse: true

    - name: Move Spicetify theme to config directroy
      shell: cp -r ~/Downloads/spicetify-themes ~/.config/spicetify/Themes

    - name: Apply Spicetify theme
      shell: spicetify config current_theme default


    #==== DOTFILES ====

    - name: Install dotfiles
      git:
        repo: https://github.com/MapManagement/dotfiles.git
        dest: ~/

    #==== DOWNLOAD AND INSTALL VIM PLUGINS ====

    - name: Install vim-plug plugins
      shell: nvim +PlugInstall +qa

    - name: Install Rust coc
      shell: nvim -c "CocInstall coc-rust-analyzer" -c "qa"

#=====================================
# GET LOCAL FILES
#=====================================

